name: fivetwelve
favicon: null
layout_spectrum: 0.0533195361495018
typography_spectrum: 0.3718884219415486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.509806550340727
  lightness: 0.6086116963997483
  saturation: 0.03149610827676952
  rhythmicContrast: 0.662136506754905
purpose: []
